version: '3'
services:
  api:
    build: .
    ports:
      - 8000:8000
    env_file:
      - ./.env

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
